const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {randomUUID}=require('node:crypto');
const {before,after,beforeEach,test}=require('node:test');
const {PGlite}=require('@electric-sql/pglite');
const {fixture}=require('../test-support/auth-fixture');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const migrations=['001_tamagotchi.sql','../seeds/tamagotchi-starters.sql','002_adoption.sql','003_time_engine.sql','004_feed.sql','005_play.sql','006_clean.sql','007_sleep.sql','008_xp_levels.sql','009_growth_stages.sql','010_coins.sql','011_discoveries.sql','012_daily_reward.sql','013_inventory.sql','014_shop.sql','015_daily_quests.sql','016_achievements.sql','017_catch_the_crumbs.sql','018_inventory_feeding.sql','019_pigeon_battles.sql','020_automatic_battles.sql','021_battle_health.sql','022_level_scaled_battle_damage.sql','023_pigeon_packs.sql','024_pigeon_clinic.sql'];
let db;
before(async()=>{db=new PGlite();await db.exec(`CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);CREATE ROLE anon NOLOGIN;CREATE ROLE authenticated NOLOGIN;CREATE ROLE service_role NOLOGIN BYPASSRLS;CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULL::uuid $$;GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;`);for(const file of migrations)await db.exec(read(file.startsWith('../')?file.slice(3):`migrations/${file}`));});
after(async()=>db?.close());beforeEach(async()=>db.exec('TRUNCATE public.game_pigeons,public.game_users,auth.users CASCADE'));
async function account(t,coins=200,health=40){const f=await fixture(t,{gameDb:db}),user=(await(await f.signup()).json()).user;await f.request('/api/game/adopt',{body:{speciesId:'jacobin pigeon',nickname:'Gilbert'}});await db.query('UPDATE public.game_users SET coins=$1 WHERE id=$2',[coins,user.id]);await db.query('UPDATE public.game_pigeons SET health=$1 WHERE user_id=$2',[health,user.id]);return {...f,user};}
const treat=(f,id=randomUUID(),extra={})=>f.request('/api/game/clinic',{body:{requestId:id,...extra}});

test('clinic restores full Health and charges the fixed server price',async t=>{const f=await account(t);const response=await treat(f),data=await response.json();assert.equal(response.status,200);assert.equal(data.treated,true);assert.equal(data.effects.health,60);assert.equal(data.effects.coins,-100);assert.equal(Number(data.pigeon.health),100);assert.deepEqual(data.wallet,{coins:100,version:1});assert.equal((await db.query('SELECT count(*) FROM public.game_clinic_receipts')).rows[0].count,1);});
test('full Health and insufficient coins never charge or create a receipt',async t=>{let f=await account(t,200,100),response=await treat(f);assert.equal(response.status,409);assert.equal((await response.json()).code,'HEALTH_FULL');await db.query('UPDATE public.game_pigeons SET health=20 WHERE user_id=$1',[f.user.id]);await db.query('UPDATE public.game_users SET coins=99 WHERE id=$1',[f.user.id]);response=await treat(f);assert.equal(response.status,409);assert.equal((await response.json()).code,'NOT_ENOUGH_COINS');assert.equal(Number((await db.query('SELECT coins FROM public.game_users')).rows[0].coins),99);assert.equal((await db.query('SELECT count(*) FROM public.game_clinic_receipts')).rows[0].count,0);});
test('identical retries and concurrent visits charge only once',async t=>{const f=await account(t),id=randomUUID();const responses=await Promise.all([treat(f,id),treat(f,id),treat(f,randomUUID())]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,200,409]);const results=await Promise.all(responses.filter(r=>r.status===200).map(r=>r.json()));assert.equal(results.filter(r=>!r.replayed).length,1);assert.equal(Number((await db.query('SELECT coins FROM public.game_users')).rows[0].coins),100);assert.equal((await db.query('SELECT count(*) FROM public.game_clinic_receipts')).rows[0].count,1);});
test('receipt failure rolls back Health and coins and permits a safe retry',async t=>{const f=await account(t);await db.exec(`CREATE FUNCTION public.reject_clinic_receipt() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'test'; END $$;CREATE TRIGGER reject_clinic_receipt BEFORE INSERT ON public.game_clinic_receipts FOR EACH ROW EXECUTE FUNCTION public.reject_clinic_receipt()`);try{assert.equal((await treat(f)).status,503);}finally{await db.exec('DROP TRIGGER reject_clinic_receipt ON public.game_clinic_receipts;DROP FUNCTION public.reject_clinic_receipt()');}assert.equal(Number((await db.query('SELECT coins FROM public.game_users')).rows[0].coins),200);assert.equal(Number((await db.query('SELECT health FROM public.game_pigeons')).rows[0].health),40);assert.equal((await treat(f)).status,200);});
test('clinic route validates session, method, origin and request ID',async t=>{const anon=await fixture(t,{gameDb:db});assert.equal((await treat(anon)).status,401);const f=await account(t);assert.equal((await f.request('/api/game/clinic',{method:'GET'})).status,405);assert.equal((await f.request('/api/game/clinic',{body:{requestId:randomUUID()},origin:'https://evil.example'})).status,403);assert.equal((await f.request('/api/game/clinic',{body:{requestId:'bad'}})).status,400);});
test('dashboard shows the clinic and its browser assets',async t=>{const f=await account(t),html=await(await f.request('/my-pigeon')).text();assert.match(html,/id="visitClinic"/);assert.match(html,/Visit clinic · ◉ 100/);assert.match(html,/pigeon-clinic\.js/);});
test('clinic function and receipts remain server-only with own-read RLS',async t=>{const f=await account(t);for(const role of ['anon','authenticated'])for(const sql of ['SELECT public.treat_game_pigeon($1,$2)',"INSERT INTO public.game_clinic_receipts(user_id,request_id,pigeon_id,price_paid,result) SELECT $1,$2,id,100,'{}' FROM public.game_pigeons WHERE user_id=$1"]){await db.exec(`SET ROLE ${role}`);await assert.rejects(db.query(sql,[f.user.id,randomUUID()]));await db.exec('RESET ROLE');}});
