const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {randomUUID}=require('node:crypto');
const {before,after,beforeEach,test}=require('node:test');
const {PGlite}=require('@electric-sql/pglite');
const {fixture}=require('../test-support/auth-fixture');
const {bundledCatalog}=require('../lib/game/discoveries');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
let db;
const migrations=['001_tamagotchi.sql','../seeds/tamagotchi-starters.sql','002_adoption.sql','003_time_engine.sql','004_feed.sql','005_play.sql','006_clean.sql','007_sleep.sql','008_xp_levels.sql','009_growth_stages.sql','010_coins.sql','011_discoveries.sql','012_daily_reward.sql','013_inventory.sql','014_shop.sql','015_daily_quests.sql','016_achievements.sql','017_catch_the_crumbs.sql','018_inventory_feeding.sql','019_pigeon_battles.sql','020_automatic_battles.sql','021_battle_health.sql','022_level_scaled_battle_damage.sql','023_pigeon_packs.sql'];
before(async()=>{db=new PGlite();await db.exec(`CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);CREATE ROLE anon NOLOGIN;CREATE ROLE authenticated NOLOGIN;CREATE ROLE service_role NOLOGIN BYPASSRLS;CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULL::uuid $$;GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;`);for(const file of migrations)await db.exec(read(file.startsWith('../')?file.slice(3):`migrations/${file}`));});
after(async()=>db?.close());beforeEach(async()=>db.exec('TRUNCATE public.game_pigeons,public.game_users,auth.users CASCADE'));
async function account(t,coins=2000){const f=await fixture(t,{gameDb:db,getCatalog:async()=>bundledCatalog()}),user=(await(await f.signup()).json()).user;await f.request('/api/game/adopt',{body:{speciesId:'jacobin pigeon',nickname:'Gilbert'}});await db.query('UPDATE public.game_users SET coins=$1 WHERE id=$2',[coins,user.id]);return {...f,user};}
const buy=(f,type,id=randomUUID(),extra={})=>f.request('/api/game/packs/buy',{body:{packType:type,requestId:id,...extra}});

test('pack status exposes the balanced prices and UTC limits',async t=>{const f=await account(t);const response=await f.request('/api/game/packs'),data=await response.json();assert.equal(response.status,200);assert.deepEqual(data.packs.map(p=>[p.id,p.size,p.price,p.duplicateRefund,p.available]),[['normal',2,300,50,true],['big',5,900,50,true]]);});
test('normal pack spends 300 coins and adds two distinct catalogue pigeons',async t=>{const f=await account(t);const response=await buy(f,'normal'),data=await response.json();assert.equal(response.status,200);assert.equal(data.pigeons.length,2);assert.equal(new Set(data.pigeons.map(p=>p.speciesId)).size,2);assert.ok(data.pigeons.every(p=>p.pigeon.hasRealImage));assert.ok(data.pigeons.every(p=>['common','uncommon','rare','epic','legendary'].includes(p.pigeon.gameRarity)));assert.equal(Number(data.wallet.coins),1700+Number(data.duplicateRefund));const rows=(await db.query('SELECT species_id FROM public.game_pigeon_discoveries WHERE user_id=$1',[f.user.id])).rows;assert.equal(rows.length,1+data.pigeons.filter(p=>p.isNew).length);});
test('big pack opens once per week and an identical retry never charges twice',async t=>{const f=await account(t),id=randomUUID();const first=await(await buy(f,'big',id)).json(),balance=Number(first.wallet.coins);assert.equal(first.pigeons.length,5);const replay=await(await buy(f,'big',id)).json();assert.equal(replay.replayed,true);assert.equal(Number(replay.wallet.coins),balance);let response=await buy(f,'big');assert.equal(response.status,409);assert.equal((await response.json()).code,'PACK_LIMIT');assert.equal((await db.query("SELECT count(*) FROM public.game_pigeon_pack_receipts WHERE pack_type='big'")).rows[0].count,1);});
test('duplicates return 50 coins each',async t=>{const f=await account(t,300);const ids=bundledCatalog().breeds.map(p=>p.id);await db.query('INSERT INTO public.game_pigeon_discoveries(user_id,species_id) SELECT $1,value FROM unnest($2::text[]) value ON CONFLICT DO NOTHING',[f.user.id,ids]);const result=await(await buy(f,'normal')).json();assert.equal(result.duplicateRefund,100);assert.equal(Number(result.wallet.coins),100);});
test('insufficient funds and invalid pack input change nothing',async t=>{const f=await account(t,299);let response=await buy(f,'normal');assert.equal(response.status,409);assert.equal((await response.json()).code,'NOT_ENOUGH_COINS');for(const body of [{packType:'legendary',requestId:randomUUID()},{packType:'normal',requestId:'bad'}]){const rejected=await f.request('/api/game/packs/buy',{body});assert.equal(rejected.status,400);}assert.equal(Number((await db.query('SELECT coins FROM public.game_users WHERE id=$1',[f.user.id])).rows[0].coins),299);assert.equal((await db.query('SELECT count(*) FROM public.game_pigeon_pack_receipts')).rows[0].count,0);});
test('shop contains both pack controls while the dashboard stays focused on care',async t=>{const f=await account(t),shop=await(await f.request('/shop')).text(),dashboard=await(await f.request('/my-pigeon')).text();assert.match(shop,/data-pack-buy="normal"/);assert.match(shop,/data-pack-buy="big"/);assert.match(shop,/pigeon-packs\.js/);assert.match(shop,/300 coins/);assert.match(shop,/900 coins/);assert.doesNotMatch(dashboard,/id="pigeonPacks"/);});
test('pack client shows rarity and celebrates epic or legendary cards',()=>{const script=read('public/pigeon-packs.js'),styles=read('public/pigeon-packs.css');assert.match(script,/Jacobin_Pigeon/);assert.match(script,/data\.pigeons\.forEach/);assert.match(script,/pack-rarity-badge/);assert.match(script,/rarity==='epic'\|\|rarity==='legendary'/);assert.match(script,/Go to PigeonDex/);assert.match(script,/pack-close-button/);assert.match(styles,/@keyframes pack-top-rip/);assert.match(styles,/@keyframes pack-card-deal/);assert.match(styles,/@keyframes rarity-firework-spark/);assert.match(styles,/prefers-reduced-motion/);});
test('pack functions and receipts remain server-only with own-read RLS',async t=>{const f=await account(t);for(const role of ['anon','authenticated'])for(const sql of ["SELECT public.buy_pigeon_pack($1,$2,'normal',ARRAY['a','b'])","SELECT public.get_pigeon_pack_status($1)","INSERT INTO public.game_pigeon_pack_receipts(user_id,request_id,pack_type,period_start,result) VALUES($1,$2,'normal',current_date,'{}')"]){await db.exec(`SET ROLE ${role}`);await assert.rejects(db.query(sql,[f.user.id,randomUUID()]));await db.exec('RESET ROLE');}});
