const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {randomUUID}=require('node:crypto');
const {before,after,beforeEach,test}=require('node:test');
const {PGlite}=require('@electric-sql/pglite');
const {fixture}=require('../test-support/auth-fixture');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const migrations=['001_tamagotchi.sql','../seeds/tamagotchi-starters.sql','002_adoption.sql','003_time_engine.sql','004_feed.sql','005_play.sql','006_clean.sql','007_sleep.sql','008_xp_levels.sql','009_growth_stages.sql','010_coins.sql','011_discoveries.sql','012_daily_reward.sql','013_inventory.sql','014_shop.sql','015_daily_quests.sql','016_achievements.sql','017_catch_the_crumbs.sql','018_inventory_feeding.sql','019_pigeon_battles.sql','020_automatic_battles.sql','021_battle_health.sql','022_level_scaled_battle_damage.sql','023_pigeon_packs.sql','024_pigeon_clinic.sql','025_more_quests_achievements.sql'];
let db;
before(async()=>{db=new PGlite();await db.exec(`CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);CREATE ROLE anon NOLOGIN;CREATE ROLE authenticated NOLOGIN;CREATE ROLE service_role NOLOGIN BYPASSRLS;CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT NULL::uuid $$;GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;`);for(const file of migrations)await db.exec(read(file.startsWith('../')?file.slice(3):`migrations/${file}`));});
after(async()=>db?.close());beforeEach(async()=>db.exec('TRUNCATE public.game_pigeons,public.game_users,auth.users CASCADE'));
async function account(t){const f=await fixture(t,{gameDb:db}),user=(await(await f.signup()).json()).user;await f.request('/api/game/adopt',{body:{speciesId:'jacobin pigeon',nickname:'Gilbert'}});return {...f,user};}

test('expanded daily list contains seven balanced quests',async t=>{const f=await account(t),data=await(await f.request('/api/game/quests')).json();assert.deepEqual(data.quests.map(q=>q.id),['feed_3','play_2','clean_1','sleep_1','battle_1','crumb_game_1','visit_pigeondex']);assert.equal(data.quests.reduce((sum,q)=>sum+q.reward.coins,0),120);});
test('sleep, battle and a completed minigame advance their new daily quests once',async t=>{const f=await account(t);assert.equal((await f.request('/api/game/sleep',{body:{requestId:randomUUID()}})).status,200);assert.equal((await f.request('/api/game/battle',{body:{requestId:randomUUID()}})).status,200);const started=await(await f.request('/api/game/crumbs/start',{body:{requestId:randomUUID()}})).json();await db.query("UPDATE public.game_crumb_runs SET started_at=clock_timestamp()-interval '31 seconds' WHERE id=$1",[started.runId]);assert.equal((await f.request('/api/game/crumbs/finish',{body:{runId:started.runId,caught:[]}})).status,200);const quests=await(await f.request('/api/game/quests')).json();for(const id of ['sleep_1','battle_1','crumb_game_1']){const quest=quests.quests.find(q=>q.id===id);assert.equal(quest.progress,1);assert.equal(quest.completed,true);}});
test('new permanent achievements use saved battles, packs, clinic visits, games and discoveries',async t=>{const f=await account(t),pigeon=(await db.query('SELECT id FROM public.game_pigeons WHERE user_id=$1',[f.user.id])).rows[0],opponent=(await db.query("SELECT id FROM public.game_species WHERE id<>'jacobin pigeon' LIMIT 1")).rows[0];await db.query("INSERT INTO public.game_battle_receipts(user_id,request_id,pigeon_id,opponent_species_id,result) SELECT $1,gen_random_uuid(),$2,$3,'{}'::jsonb FROM generate_series(1,10)",[f.user.id,pigeon.id,opponent.id]);await db.query("INSERT INTO public.game_pigeon_pack_receipts(user_id,request_id,pack_type,period_start,result) SELECT $1,gen_random_uuid(),CASE WHEN g%2=0 THEN 'normal' ELSE 'big' END,current_date-g,'{}'::jsonb FROM generate_series(1,10) g",[f.user.id]);await db.query("INSERT INTO public.game_clinic_receipts(user_id,request_id,pigeon_id,price_paid,result) SELECT $1,gen_random_uuid(),$2,100,'{}'::jsonb FROM generate_series(1,5)",[f.user.id,pigeon.id]);await db.query("INSERT INTO public.game_crumb_runs(id,user_id,request_id,started_at,duration_seconds,schedule,completed_at,score,coins_awarded,xp_awarded,result) SELECT gen_random_uuid(),$1,gen_random_uuid(),clock_timestamp()-interval '1 minute',30,public.crumb_game_schedule(gen_random_uuid()),clock_timestamp(),0,0,0,'{}'::jsonb FROM generate_series(1,10)",[f.user.id]);await db.query("INSERT INTO public.game_pigeon_discoveries(user_id,species_id) SELECT $1,'test-pigeon-'||g FROM generate_series(1,99) g ON CONFLICT DO NOTHING",[f.user.id]);const data=await(await f.request('/api/game/achievements')).json();assert.equal(data.total,10);for(const id of ['arena_regular','pack_opener','clinic_friend','crumb_champion','master_birder'])assert.equal(data.achievements.find(a=>a.id===id).unlocked,true,id);const claim=await f.request('/api/game/achievements/claim',{body:{achievementId:'arena_regular'}}),reward=await claim.json();assert.equal(claim.status,200);assert.deepEqual(reward.effects,{coins:150,xp:75});});
