-- Phase 3. Apply after 001_tamagotchi.sql and seeds/tamagotchi-starters.sql.
-- Preserves accounts, existing pigeons and the original species records.
BEGIN;
SET LOCAL standard_conforming_strings = on;

ALTER TABLE public.game_species ADD COLUMN kind text NOT NULL DEFAULT 'species';
ALTER TABLE public.game_species ADD COLUMN parent_species_id text
  REFERENCES public.game_species(id) ON DELETE RESTRICT;
ALTER TABLE public.game_species DROP CONSTRAINT game_species_id_check;
ALTER TABLE public.game_species ADD CONSTRAINT game_species_taxonomy_check CHECK (
  (kind = 'species' AND id ~ '^birdnet:BN[0-9]+$' AND parent_species_id IS NULL)
  OR (kind = 'breed' AND length(btrim(id)) > 0 AND parent_species_id IS NOT NULL AND id <> parent_species_id)
);
COMMENT ON COLUMN public.game_species.kind IS 'Catalogue record kind: species or domestic breed.';

-- BEGIN GENERATED STARTERS
-- Source: data/domestic-pigeons.json. Generated by scripts/seed-adoption.js.
UPDATE public.game_species SET is_starter = false WHERE is_starter;
INSERT INTO public.game_species (
  id, name, kind, parent_species_id, scientific_name, description, image,
  rarity, is_starter, source_url, description_source, description_url, image_attribution
)
SELECT id, name, kind, parent_species_id, scientific_name, description, image,
  rarity, is_starter, source_url, description_source, description_url, image_attribution
FROM jsonb_to_recordset('[{"id":"jacobin pigeon","name":"Jacobin pigeon","kind":"breed","parent_species_id":"birdnet:BN03514","scientific_name":"Columba livia","description":"The Jacobin is a breed of fancy pigeon developed over many years of selective breeding that originated in Asia. Jacobins, along with other varieties of domesticated pigeons, are all descendants of the rock pigeon (Columba livia).","image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/A_Jacobin_Pigeon.JPG/960px-A_Jacobin_Pigeon.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail","rarity":"common","is_starter":true,"source_url":"https://en.wikipedia.org/wiki/Jacobin_pigeon","description_source":"Wikipedia","description_url":"https://en.wikipedia.org/wiki/Jacobin_pigeon","image_attribution":{"artist":"Captaincid","sourceUrl":"https://commons.wikimedia.org/wiki/File:A_Jacobin_Pigeon.JPG","license":"CC BY-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/4.0/"}},{"id":"indian fantail","name":"Indian Fantail","kind":"breed","parent_species_id":"birdnet:BN03514","scientific_name":"Columba livia","description":"The Indian Fantail is a breed of fancy pigeon developed over many years of selective breeding. Indian Fantails, along with other varieties of domesticated pigeons, are all descendants of the rock dove (Columba livia).","image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Indian_fantail%28black_self%29.jpg/960px-Indian_fantail%28black_self%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail","rarity":"common","is_starter":true,"source_url":"https://en.wikipedia.org/wiki/Indian_Fantail","description_source":"Wikipedia","description_url":"https://en.wikipedia.org/wiki/Indian_Fantail","image_attribution":{"artist":"jim gifford","sourceUrl":"https://commons.wikimedia.org/wiki/File:Indian_fantail(black_self).jpg","license":"CC BY-SA 2.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/2.0/"}},{"id":"australian saddleback tumbler","name":"Australian Saddleback Tumbler","kind":"breed","parent_species_id":"birdnet:BN03514","scientific_name":"Columba livia","description":"The Australian Saddleback Tumbler is a breed of fancy pigeon developed over many years of selective breeding. Australian Saddleback Tumblers, along with other varieties of domesticated pigeons, are all descendants of the rock pigeon (Columba livia).","image":"https://upload.wikimedia.org/wikipedia/commons/c/cd/Australian_saddleback_tumbler.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled","rarity":"common","is_starter":true,"source_url":"https://en.wikipedia.org/wiki/Australian_Saddleback_Tumbler","description_source":"Wikipedia","description_url":"https://en.wikipedia.org/wiki/Australian_Saddleback_Tumbler","image_attribution":{"artist":"jim gifford","sourceUrl":"https://commons.wikimedia.org/wiki/File:Australian_saddleback_tumbler.jpg","license":"CC BY-SA 2.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/2.0/"}}]'::jsonb) AS breed (
  id text, name text, kind text, parent_species_id text, scientific_name text, description text, image text,
  rarity text, is_starter boolean, source_url text, description_source text, description_url text, image_attribution jsonb
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, kind = EXCLUDED.kind, parent_species_id = EXCLUDED.parent_species_id,
  scientific_name = EXCLUDED.scientific_name, description = EXCLUDED.description, image = EXCLUDED.image,
  is_starter = EXCLUDED.is_starter, source_url = EXCLUDED.source_url,
  description_source = EXCLUDED.description_source, description_url = EXCLUDED.description_url,
  image_attribution = EXCLUDED.image_attribution;
-- END GENERATED STARTERS

CREATE FUNCTION public.adopt_game_pigeon(p_user_id uuid, p_species_id text, p_nickname text)
RETURNS SETOF public.game_pigeons
LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
DECLARE
  existing public.game_pigeons%ROWTYPE;
BEGIN
  IF p_nickname IS NULL OR char_length(p_nickname) NOT BETWEEN 1 AND 32
    OR p_nickname <> btrim(p_nickname) OR p_nickname ~ '[[:cntrl:]]' THEN
    RAISE EXCEPTION 'Invalid nickname' USING ERRCODE = '22023';
  END IF;
  -- Lock the profile before checking existence: simultaneous requests serialize.
  PERFORM id FROM public.game_users WHERE id = p_user_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Profile required' USING ERRCODE = '23503';
  END IF;
  SELECT * INTO existing FROM public.game_pigeons WHERE user_id = p_user_id;
  IF FOUND THEN
    -- An exact retry returns the saved row without changing progress or timestamps.
    IF existing.species_id = p_species_id AND existing.nickname = p_nickname THEN
      RETURN NEXT existing;
      RETURN;
    END IF;
    RAISE EXCEPTION 'Already adopted' USING ERRCODE = '23505';
  END IF;
  PERFORM id FROM public.game_species WHERE id = p_species_id AND is_starter FOR SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unavailable starter' USING ERRCODE = '22023';
  END IF;
  -- All stats, level, XP and timestamps come from database defaults.
  RETURN QUERY INSERT INTO public.game_pigeons (user_id, species_id, nickname)
    VALUES (p_user_id, p_species_id, p_nickname) RETURNING *;
END;
$$;
REVOKE ALL ON FUNCTION public.adopt_game_pigeon(uuid, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.adopt_game_pigeon(uuid, text, text) TO service_role;
NOTIFY pgrst, 'reload schema';
COMMIT;
